#ifndef COMPONENTS_WEATHER_MANAGER_INCLUDE_WEATHER_ICONS_H_
#define COMPONENTS_WEATHER_MANAGER_INCLUDE_WEATHER_ICONS_H_

enum weather_icons {
    UNKNOWN,
    CLEAR_SKY_DAY,
    CLEAR_SKY_NIGHT,
    FEW_CLOUDS_DAY,
    FEW_CLOUDS_NIGHT,
    CLOUDS,
    SHOWER_RAIN,
    RAIN,
    THUNDERSTORM,
    SNOW,
    FOG
}; 

#endif 